# Generated by Django 4.1.1 on 2022-10-05 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_date_of_birth'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='bvn',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='email',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='last_name',
        ),
        migrations.AddField(
            model_name='wallet',
            name='account_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='wallet',
            name='account_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='wallet',
            name='bank',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.customuser'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
