# Generated by Django 4.1.1 on 2022-10-05 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_customuser_date_of_birth'),
        ('wallet', '0002_remove_wallet_bvn_remove_wallet_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.customuser'),
        ),
    ]
